config/routes.rb
FashionStartup::Application.routes.draw do
  resources :sponsors, only: [:show]

  resources :mailer_volunteers

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :startups, only: [:show]
  # resources :spotlights, only: [:update]
  # resources :sponsor_spotlights, only: [:update]
  resources :teams, only: [:index]
  resources :interested_startups, only: [:create, :new]
  resources :all_sponsors, only: [:index]
  resources :events, only: [:index]
  resources :event_spotlights, only: [:show]
  resources :participants, only: [:index]
  resources :contest, only: [:show]
  resources :media, only: [:index]
  resources :features, only: [:show]


  root 'welcome#index'
  get 'welcome/about'
  get 'welcome/contact'
  get 'welcome/team'
  get 'welcome/subscribe'

  resources :welcome
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/all_sponsor.rb
class AllSponsor < ActiveRecord::Base
  mount_uploader :sponsor_logo, SponsorLogoUploader

  def self.level_options
    return ["Platinum", "Gold", "Silver", "Bronze", "Partners"]
  end

  scope :platinum, -> { where(level: 'platinum')}
  scope :gold, -> { where(level: 'gold')}
  scope :silver, -> { where(level: 'silver')}
  scope :bronze, -> { where(level: 'bronze')}
  scope :partners, -> { where(level: 'partners')}

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  validates_presence_of :contest_code
end

app/models/event.rb
class Event < ActiveRecord::Base
  default_scope order('start_time ASC')

  validates_presence_of :date, :event_name, :description, :link, :start_time, :end_time
end

app/models/event_spotlight.rb
class EventSpotlight < ActiveRecord::Base
  validates_presence_of :eventbrite_code
end

app/models/feature.rb
class Feature < ActiveRecord::Base

  def self.startup
    Startup.find(find_by(featurable_type: 'startup').featurable_id) ||
    Startup.limit(1).order('RANDOM()')
  end

  def self.sponsor
    Sponsor.find(find_by(featurable_type: 'sponsor').featurable_id) ||
    Sponsor.limit(1).order('RANDOM()')
  end

  def self.find_startup
    find_by_feature_type('startup')
  end

  def self.find_sponsor
    find_by_feature_type('sponsor')
  end

private

  def self.find_by_feature_type(type)
    find_or_create_by(featurable_type: type)
  end

end

app/models/feature_box.rb
class FeatureBox < ActiveRecord::Base
  mount_uploader :feature_photo, FeaturePhotoUploader

  validates :name, presence: true
  validates :feature_photo,   presence: true
  validates :feature_content, presence: true

  def featured
    send(self.name)
  end

  def startup
    Feature.startup
  end

  def sponsor
    Feature.sponsor
  end

  def event
    EventSpotlight.first
  end

  def contest
    Contest.first
  end

end

app/models/fp_codebox.rb
class FpCodebox < ActiveRecord::Base
end

app/models/interested_startup.rb
class InterestedStartup < ActiveRecord::Base
  mount_uploader :logo, LogoUploader
  mount_uploader :cover_image, CoverImageUploader
  validates_presence_of :name, :contactname, :email, :logo, :website, :facebook_link,
    :twitter_link, :advice, :elevator_pitch, :challenge, :cover_image
  validates_uniqueness_of :name
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
end

app/models/mailer_volunteer.rb
class MailerVolunteer < ActiveRecord::Base
end

app/models/media.rb
class Media < ActiveRecord::Base
  mount_uploader :pdf_files, PdfFilesUploader
  mount_uploader :cover_image, PictureUploader
  validates_presence_of :select_one

  scope :media_inquires, -> { where(select_one: 'media inquires')}
  scope :press_releases, -> { where(select_one: 'press releases')}
  scope :media_partners, -> { where(select_one: 'media partners')}
  scope :media_coverage, -> { where(select_one: 'media coverage')}
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  mount_uploader :headshot, HeadshotUploader
  validates_presence_of :title, :name, :headshot

  scope :digital_fashion_demo_presenters, -> { where(title: 'oct. 7 -digital fashion demo presenters')}
  scope :conference_speakers, -> { where(title: 'oct. 8 -conference speakers')}
  scope :startup_emerging_designers, -> { where(title: 'Oct. 9 -Startup/Emerging Designers')}
  scope :digital_fashion_startups, -> { where(title: 'Oct. 9 -Digital Fashion Startups')}
  scope :exhibitors_lounge_partners, -> { where(title: 'Oct. 9 -Exhibitors/Demo Lounge Partners')}
  scope :runway_models, -> { where(title: 'Oct. 9 Runway Models')}
  
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  mount_uploader :logo, LogoUploader
  mount_uploader :cover_image, CoverImageUploader

  validates_presence_of :name, :description, :url, :cover_image, :logo
  validates_uniqueness_of :name
end

app/models/sponsor_spotlight.rb
class SponsorSpotlight < ActiveRecord::Base
  def sponsor_featured
    return Sponsor.find(sponsor_id)
  end
end

app/models/spotlight.rb
class Spotlight < ActiveRecord::Base

  def currently_featured
    return Startup.find(startup_id)
  end

end

app/models/startup.rb
class Startup < ActiveRecord::Base
  mount_uploader :logo, LogoUploader
  mount_uploader :cover_image, CoverImageUploader

  validates_presence_of :name, :facebook_link, :advice, :elevator_pitch,
    :logo, :cover_image, :twitter_link, :challenge, :website

  validates_uniqueness_of :name


end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }
  validates_uniqueness_of :email
  validates_presence_of :email
end

app/models/team.rb
class Team < ActiveRecord::Base
  mount_uploader :picture, PictureUploader

  validates_presence_of :name, :role, :picture

  scope :management_team, -> { where(status: 'management team')}
  scope :advisory_board, -> { where(status: 'advisory board')}

end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  validates_presence_of :position
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @subscriber = Subscriber.new
    @codebox = FpCodebox.find(1)
    @feature_boxes = FeatureBox.all.order(id: :asc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def site_name
    "Startup Fashion Week"
  end

  def titler(page_title)
    page_title.empty? ? site_name : "#{site_name} | #{page_title}"
  end

end

app/views/welcome/_feature_box.html.erb
<div class="small-6 medium-6 large-3 column">

  <div class="thumbnail" style="background-image: url('<%= fb.feature_photo_url.to_s %>')" data-frame data-ratio="1x1">

    <div class="hover">
      <%= link_to fb.featured, class: "caption" do %>
        <p><%= fb.feature_content %></p>
      <% end %>
    </div>

  </div>
  <h6 class="panel" id="panel-label"><%= link_to "#{fb.name} Spotlight", fb.featured %></h6>

</div>

app/views/welcome/about.html.erb
<div id="about" class="wrapper">
<div class="row">
<div class="row">
  <div class="medium-3 column">

    <!-- sidebar -->
    <aside class="sidebar">
      <ul>
        <li><a href="#AboutUs">About Us</a></li>
        <li><a href="#AboutEvent">About the Event</a></li>
      </ul>
    </aside>

  </div>
  <div class="medium-9 column">

    <!-- about content -->
    <content class="content">
      <h2><a name="AboutUs">About Us</a></h2>

      <p>Did you know that many entrepreneurs in the Fashion Industry do not have any formal training/education in business? For many it’s a passion that they decided to pursue by taking a risk, often learning from experience. It isn't until entrepreneurs are in the thick of launching their product, collection or brand that they realize they are knee deep in a very complicated world of Business. At this point, most entrepreneurs cannot commit the time or resources to obtain proper training and often this leads to big, expensive mistakes. We want entrepreneurs to thrive and for the economy to develop and flourish. It takes a community to run a business in the Fashion Industry – and we want to support startup entrepreneurs by providing a one week program filled with events that will help them connect, launch and accelerate.</p>

      <p>We also recognize that the Fashion Industry is changing. It’s no longer just about Designers, Manufacturers, Stylists etc.  There is also an emerging growth of Retail-Tech, Fashion-Tech and Wearable-Tech startups globally. The commonality between all sectors is the need for business skills to survive in this Industry.</p>

      <p>Startup Fashion Week is planning an unforgettable event for Oct. 7-9 2014 in Toronto. We will officially launch a full week program in 2015!  Why Toronto? Because there is a plethora of talent, Industry professionals and a vibrant startup community. It is possible that Startup Fashion Week will take place in different cities across North America afterward to help other Fashion entrepreneurs succeed. To be updated on dates, contests, venue and programming please be sure to sign up for our mailing list <%= link_to "HERE", welcome_subscribe_path, id: 'email_links' %></p>

      <p>Startup Fashion Week is organized by a team of Fashion Industry Professionals, Startup Entrepreneurs, Students and Volunteers. Want to get involved? Send us an email: <a href="mailto:info@startupfashionweek.com?subject=I%20want%20to%20get%20involved%20with%20SFW!" id="email_links">INFO@STARTUPFASHIONWEEK.COM </a> and tell us how you'd like to be a part of this extraordinary event!</p>
      <!-- about us ended here -->

      <h2><a name="AboutEvent">About The Event</a></h2>

      <p>Are you a visionary, early stage or later stage Startup in Fashion, Fashion-Tech or Wearable-Tech? (Startups are anywhere from idea phase to 7 years post launch). Have you experienced challenges finding resources to start or accelerate your business? Have you had days where you felt like giving up? Well believe us, you are NOT alone! We are dedicated to bring aspiring and new entrepreneurs in Fashion design, Fashion-Tech and Wearable-Tech a quick glimpse of the skills they need to build a successful business. We also provide resources, exposure and Industry connections for entrepreneurs.</p>

      <p>Startup Fashion Week will offer guests an array of events ranging from full day conferences, runway showcases, workshops, VIP receptions, a closing party and MUCH more! Entrepreneurs who attend Startup Fashion Week will feel a sense of direction, confidence and understand where to access the right resources to sustain the right level of success. The event itself will promote many local businesses / startups / schools. Have a startup or business that you would like to promote to help make this event a success? Pitch us: <a href="mailto:info@startupfashionweek.com?subject=Here's%20my%20pitch!" id="email_links">INFO@STARTUPFASHIONWEEK.COM </a></p>
      <!-- about event end here -->

    </content>

  </div>
</div>

<!-- message ticker -->
<%= render 'layouts/message_ticker' %>

</div>
</div>

app/views/welcome/contact.html.erb
<div id="contact" class="wrapper">
<div class="row">
<div class="row">
  <div class="medium-3 column">
    <!-- side bar -->
    <aside class="sidebar">
      <ul>
        <li><a href="#General">General Inquiries</a></li>
        <li><a href="#Volunteers">Volunteers</a></li>
        <li><a href="#Designers">Designers</a></li>
        <li><a href="#Vendors">Vendors</a></li>
      </ul>
    </aside>
  </div>
  <div class="medium-9 column">
    <!-- content -->
    <content class="content">
      <h1>CONTACT US</h1>
      <hr></hr>
      <h3><a name="General">GENERAL INQUIRIES:</a></h3>
      <p>For all general inquiries please contact us: <a href="mailto:info@startupfashionweek.com?subject= General%20inquiries%20for%20SFW" id="email_links">INFO@STARTUPFASHIONWEEK.COM </a>
      <hr></hr>

      <h3><a name="Volunteers">VOLUNTEERS:</a></h3>
      <p>If you would like to volunteer for the planning of Startup Fashion Week or during the events please send us an email to: <a href="mailto:info@startupfashionweek.com?subject= I%20would%20like%20to%20volunteer%20for%20SFW!" id="email_links">VOLUNTEERS@STARTUPFASHIONWEEK.COM </a></p>


      <p>Please include a link to your Linkedin Profile - or attach a resume and answer the following three questions:</p>

      <ol id="number_list">
        <li>What is your availability?</li>
        <li>What experience do you have with event production or fashion?</li>
        <li>What do you hope to do or learn as a volunteer?</li>
      </ol>

      <hr></hr>

        <h3><a name="Designers">DESIGNERS:</a></h3>
        <p>If you are a startup designer who would like to showcase your collection at Startup Fashion Week, please send an email to:  <a href="mailto:info@startupfashionweek.com?subject= I%20would%20like%20to%20showcase%20my%20work%20at%20SFW!" id="email_links">EVENTS@STARTUPFASHIONWEEK.COM</a></p>
        <p>Please include a link to your website along with any lookbooks or press releases regarding your latest work.</p>

        <hr></hr>

        <h3><a name="Vendors">VENDORS / SPONSORS</a></h3>

        <p>If you would like to showcase your business as a vendor or sponsor please send us an email at: <a href="mailto:info@startupfashionweek.com?subject= Vendor%20or%20sponsor%20inquiry" id="email_links">SPONSORS@STARTUPFASHIONWEEK.COM</a> with a link to your website and we will send you the vendor / sponsor package. </p>
      </div>
    </content>
  </div>
<%= render 'layouts/message_ticker' %>
</div>

</div>
</div>

app/views/welcome/index.html.erb
<!-- for margin top and bottom: 30px -->
<div id="welcome" class="wrapper">

<!-- do NOT remove this row is use to clear the inner padding -->
<div class="row">

  <!-- 1st row -->
  <div class="row">
    <div class="medium-9 large-9 column">

      <!-- flixel -->
      <div id="flixel" class="container" data-frame data-ratio="16x9">
      </div>

    </div>
    <div class="medium-3 large-3 column">

      <!-- feature-sponsor-content -->
      <div id="feature-sponsor" data-equalize-watch data-equalize-target="#flixel" data-equalize-except="mobile">
        <div class="table">
          <div class="content table-inner">
            <%= raw RedCloth.new(@codebox.codebox).to_html -%>
          </div>
        </div>
      </div>

    </div>
  </div>
  <!-- 2nd row -->
  <%= render 'layouts/message_ticker' %>

  <div class="row">
    <div class="thumbnails">
      <!-- thumbnails -->
      <% @feature_boxes.each do |fb| %>
        <%= render 'feature_box', fb: fb %>
      <% end %>

    </div>
  </div>
  <div class="thumbnails">
    <iframe src="//epilogger.com/widget/startup-fashion-week" scrolling="no" frameborder="0" style="overflow:hidden; width:950px; height:700px;"></iframe>
  </div>  
  <div class="row">
    <div class="small-12 column">
      <div class="headline"><h2 class="headline2">Fashion | Technology | Business</h2></div>
    </div>
  </div>

</div>
</div><!-- end of wrapper -->


<!-- <div class="space"><iframe src="http://epilogger.com/events/epilogger?width=800&height=700" scrolling="no" frameborder="0" style="overflow:hidden; width:900px; height:700px;"></iframe></div> -->

app/views/welcome/media.html.erb
<div id="media" class="wrapper">
<div class="row">
<div class="row">
  <div class="medium-3 column">
    <aside class="sidebar">
      <ul>
        <li><a href="#MediaInquires">Media Inquires</a></li>
        <li><a href="#PressReleases">Press Releases</a></li>
        <li><a href="#MediaPartners">Media Partners</a></li>
      </ul>
    </aside>
  </div>
  <div class="medium-9 column">
    <content class="content">
      <h1>MEDIA</h1>
      <h2><a name="MediaInquires">Media Inquires</a></h2>
      <p>For all Media Inquiries, Interviews and Event Registration please contact us: media@startupfashionweek.com (have it redirect to info@startupfashionweek.com with the subject MEDIA</p>
      <h2><a name="PressReleases">Press Releases</a></h2>
      <p>Press Releases - In this section I should be able to upload PDF's for people to download.  The PDF's should just be in rectangular windows as shown.</p>
      <h2><a name="MediaPartners">Media Partners</a></h2>
      <p>Media Partners - In this section I should be able to upload logos and they should be aligned with the above windows.</p>
    </content>
  </div>
</div>
<%= render 'layouts/message_ticker' %>
</div>
</div>

app/views/welcome/subscribe.html.erb
<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
    #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
    /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
       We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="http://startupfashionweek.us8.list-manage.com/subscribe/post?u=7b31bc913f4e…" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <h2>Subscribe to our mailing list</h2>
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
    <label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
    <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
    <label for="mce-FNAME">First Name  <span class="asterisk">*</span>
</label>
    <input type="text" value="" name="FNAME" class="required" id="mce-FNAME">
</div>
<div class="mc-field-group">
    <label for="mce-LNAME">Last Name  <span class="asterisk">*</span>
</label>
    <input type="text" value="" name="LNAME" class="required" id="mce-LNAME">
</div>
    <div id="mce-responses" class="clear">
        <div class="response" id="mce-error-response" style="display:none"></div>
        <div class="response" id="mce-success-response" style="display:none"></div>
    </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;"><input type="text" name="b_7b31bc913f4e5517d67981685_015e613243" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
</form>
</div>
<script type="text/javascript">
var fnames = new Array();var ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';
try {
    var jqueryLoaded=jQuery;
    jqueryLoaded=true;
} catch(err) {
    var jqueryLoaded=false;
}
var head= document.getElementsByTagName('head')[0];
if (!jqueryLoaded) {
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = '//ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js';
    head.appendChild(script);
    if (script.readyState && script.onload!==null){
        script.onreadystatechange= function () {
              if (this.readyState == 'complete') mce_preload_check();
        }
    }
}

var err_style = '';
try{
    err_style = mc_custom_error_style;
} catch(e){
    err_style = '#mc_embed_signup input.mce_inline_error{border-color:#6B0505;} #mc_embed_signup div.mce_inline_error{margin: 0 0 1em 0; padding: 5px 10px; background-color:#6B0505; font-weight: bold; z-index: 1; color:#fff;}';
}
var head= document.getElementsByTagName('head')[0];
var style= document.createElement('style');
style.type= 'text/css';
if (style.styleSheet) {
  style.styleSheet.cssText = err_style;
} else {
  style.appendChild(document.createTextNode(err_style));
}
head.appendChild(style);
setTimeout('mce_preload_check();', 250);

var mce_preload_checks = 0;
function mce_preload_check(){
    if (mce_preload_checks>40) return;
    mce_preload_checks++;
    try {
        var jqueryLoaded=jQuery;
    } catch(err) {
        setTimeout('mce_preload_check();', 250);
        return;
    }
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = 'http://downloads.mailchimp.com/js/jquery.form-n-validate.js';
    head.appendChild(script);
    try {
        var validatorLoaded=jQuery("#fake-form").validate({});
    } catch(err) {
        setTimeout('mce_preload_check();', 250);
        return;
    }
    mce_init_form();
}
function mce_init_form(){
    jQuery(document).ready( function($) {
      var options = { errorClass: 'mce_inline_error', errorElement: 'div', onkeyup: function(){}, onfocusout:function(){}, onblur:function(){}  };
      var mce_validator = $("#mc-embedded-subscribe-form").validate(options);
      $("#mc-embedded-subscribe-form").unbind('submit');//remove the validator so we can get into beforeSubmit on the ajaxform, which then calls the validator
      options = { url: 'http://startupfashionweek.us8.list-manage.com/subscribe/post-json?u=7b31bc9…=?', type: 'GET', dataType: 'json', contentType: "application/json; charset=utf-8",
                    beforeSubmit: function(){
                        $('#mce_tmp_error_msg').remove();
                        $('.datefield','#mc_embed_signup').each(
                            function(){
                                var txt = 'filled';
                                var fields = new Array();
                                var i = 0;
                                $(':text', this).each(
                                    function(){
                                        fields[i] = this;
                                        i++;
                                    });
                                $(':hidden', this).each(
                                    function(){
                                        var bday = false;
                                        if (fields.length == 2){
                                            bday = true;
                                            fields[2] = {'value':1970};//trick birthdays into having years
                                        }
                                        if ( fields[0].value=='MM' && fields[1].value=='DD' && (fields[2].value=='YYYY' || (bday && fields[2].value==1970) ) ){
                                            this.value = '';
                                        } else if ( fields[0].value=='' && fields[1].value=='' && (fields[2].value=='' || (bday && fields[2].value==1970) ) ){
                                            this.value = '';
                                        } else {
                                            if (/\[day\]/.test(fields[0].name)){
                                                this.value = fields[1].value+'/'+fields[0].value+'/'+fields[2].value;
                                            } else {
                                                this.value = fields[0].value+'/'+fields[1].value+'/'+fields[2].value;
                                            }
                                        }
                                    });
                            });
                        $('.phonefield-us','#mc_embed_signup').each(
                            function(){
                                var fields = new Array();
                                var i = 0;
                                $(':text', this).each(
                                    function(){
                                        fields[i] = this;
                                        i++;
                                    });
                                $(':hidden', this).each(
                                    function(){
                                        if ( fields[0].value.length != 3 || fields[1].value.length!=3 || fields[2].value.length!=4 ){
                                            this.value = '';
                                        } else {
                                            this.value = 'filled';
                                        }
                                    });
                            });
                        return mce_validator.form();
                    },
                    success: mce_success_cb
                };
      $('#mc-embedded-subscribe-form').ajaxForm(options);


    });
}
function mce_success_cb(resp){
    $('#mce-success-response').hide();
    $('#mce-error-response').hide();
    if (resp.result=="success"){
        $('#mce-'+resp.result+'-response').show();
        $('#mce-'+resp.result+'-response').html(resp.msg);
        $('#mc-embedded-subscribe-form').each(function(){
            this.reset();
        });
    } else {
        var index = -1;
        var msg;
        try {
            var parts = resp.msg.split(' - ',2);
            if (parts[1]==undefined){
                msg = resp.msg;
            } else {
                i = parseInt(parts[0]);
                if (i.toString() == parts[0]){
                    index = parts[0];
                    msg = parts[1];
                } else {
                    index = -1;
                    msg = resp.msg;
                }
            }
        } catch(e){
            index = -1;
            msg = resp.msg;
        }
        try{
            if (index== -1){
                $('#mce-'+resp.result+'-response').show();
                $('#mce-'+resp.result+'-response').html(msg);
            } else {
                err_id = 'mce_tmp_error_msg';
                html = '<div id="'+err_id+'" style="'+err_style+'"> '+msg+'</div>';

                var input_id = '#mc_embed_signup';
                var f = $(input_id);
                if (ftypes[index]=='address'){
                    input_id = '#mce-'+fnames[index]+'-addr1';
                    f = $(input_id).parent().parent().get(0);
                } else if (ftypes[index]=='date'){
                    input_id = '#mce-'+fnames[index]+'-month';
                    f = $(input_id).parent().parent().get(0);
                } else {
                    input_id = '#mce-'+fnames[index];
                    f = $().parent(input_id).get(0);
                }
                if (f){
                    $(f).append(html);
                    $(input_id).focus();
                } else {
                    $('#mce-'+resp.result+'-response').show();
                    $('#mce-'+resp.result+'-response').html(msg);
                }
            }
        } catch(e){
            $('#mce-'+resp.result+'-response').show();
            $('#mce-'+resp.result+'-response').html(msg);
        }
    }
}

</script>
<!--End mc_embed_signup-->